// <auto-generated />
using System;
using DataBaseContext.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBaseContext.Migrations
{
    [DbContext(typeof(DataBaseContext.Entities.DataBaseContext))]
    [Migration("20200518032001_ExpenceEntityRenameProp")]
    partial class ExpenceEntityRenameProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataBaseContext.Entities.BillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("DataBaseContext.Entities.ExpenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdentityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Expence");
                });

            modelBuilder.Entity("DataBaseContext.Entities.ExpenceItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenceEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("GoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenceEntityId");

                    b.HasIndex("GoodId");

                    b.ToTable("ExpenceItem");
                });

            modelBuilder.Entity("DataBaseContext.Entities.GoodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Good");
                });

            modelBuilder.Entity("DataBaseContext.Entities.ExpenceItemEntity", b =>
                {
                    b.HasOne("DataBaseContext.Entities.ExpenceEntity", null)
                        .WithMany("Goods")
                        .HasForeignKey("ExpenceEntityId");

                    b.HasOne("DataBaseContext.Entities.GoodEntity", "Good")
                        .WithMany()
                        .HasForeignKey("GoodId");
                });
#pragma warning restore 612, 618
        }
    }
}
